<h2>Apocalypse Reviews from the Edinburgh Fringe 2005</h2>
<p>Review highlights from the 2005 Edinburgh Fringe run of <i>Apocalypse: The Musical</i>. Full reviews are below.</p>
<ul>
<li>"Marvellously enjoyable" -Fest</li>
<li>"A delightful bit of late-night entertainment... the best musical laugh you'll get on the Fringe." -British Theatre Guide *****</li>
<li>"Hysterically funny... a riotous romp featuring some of the most absurdly funny one-liners ever attributed to Satan." -Edinburgh Evening News</li>
<li>"More 'jazz' hands than the most exuberant rendition of Chicago.... an energetic gem of a show." -Three Weeks ****</li>
<li>"Go buy a ticket for Apocalypse The Musical now. It's the funniest musical ever. Period... if you miss this, you'll be missing one of Fringe's best shows in nearly a decade." Broadwaybaby ***** </li>
<li>"An enjoyable late-night diversion... and the devil doesn't get all the best tunes." -The Herald</li>
</ul>
<hr />
<h3>Broadway Baby</h3>

<p><i>(Apocalypse: The Musical </i>is the only show ever to get a five star plus rating from Broadway Baby. In their own words, “Occasionally, and that's <i>very</i> occasionally, we'll come across a show that is just better than Five Stars. That's why we've have the Five Star Plus category for the absolutely stand-out productions that define new standards. If you spot a Five Star Plus review on Broadway Baby, it means you absolutely must see this production.”)</p>

<p>The world ends in 24 hours. Fight to get a ticket.</p>
<p>Ok, let's get this out of the way at the start. Go buy a ticket for <i>Apocalypse: The Musical </i>now. It's the funniest musical ever. Period.</p>
<p>Still here? Not at the box office yet? Shame on you, since if you miss this, you'll be missing one of the Fringe's best shows in nearly a decade.</p>
<p>Little Shop of Horrors meets Monty Python in this tale of biblical proportions. Satan convinces God that it's time to start again. Humankind haven't really got much right since Noah, so the end of the world is not only nigh, it's positively overdue.</p>
<p>God and Satan strike a bargain over who sits in the big chair next time around. Whoever amasses the larger army through a single human recruiter wins the pot. God chooses Charlie, a plucky Milkman with a herd of unusually friendly cows to pass blessed milk around, whilst Satan picks Wendy - a whore who is more Natalie Wood than Mae West - to recruit by kissing folk. What ensues is a madcap, hilariously funny and totally unmissable satire, which had me in fits from start to finish. I literally cried.</p>
<p>The cast are phenomenally talented. They belt out bubble-gum musical numbers with wickedly cheeky lyrics, whilst a chorus of cows and nuns dance side-splittingly choreographed routines. The individual performances are outstanding. Christian Carter's facial expressions alone, in his role as Daisy the cow, is comic genius. Mark Stanford's portrayal of Charlie the Milkman is worthy of a West End stage. They can sing, they can dance and they can act. I should hate them. This is a show well worth staying up late to catch.</p>
<h3>Three Weeks</h3>
<p>Dancing cows, kidnapping nuns and a suspiciously limp-wristed Satan; I bet Nostradamus never saw that coming. Apocalypse: The Musical has God and Satan's ultimate showdown playing out to a bassy, funked up soundtrack, executing rock 'n' gospel numbers at every opportunity. Baffling in its absurdity, the show is performed, tongues firmly in cheek, by a marvellous all singing, all dancing cast whose 'Waltons-meets-Brady Bunch-dialogue' juxtaposes the worlds' impending doom, whilst the choreography pirouettes itself straight from the cabaret stage with more 'jazz' hands than the most exuberant rendition of Chicago. There may be five or six too many songs for the musical haters out there, but for everyone else, it's an energetic gem of a show. </p>
<h3>Edinburgh Evening News</h3>
<p>The apocalypse is not the most obvious backdrop for a boy-meets-girl musical. But then, traditionally, the boy would not be Charlie, a milkman hired by God to recruit a divine army to fight in the ultimate cosmic battle, and he would almost certainly not fall in love with an illiterate prostitute, summoned by a flipchart-wielding devil to seduce the opposing team.</p>
<p>Newton and Merry's script parodies the traditional musical in a clever, and often hysterically funny way. The opening number sees Charlie singing about the wonders of milk, backed by gurning, spacehopper-riding cows, while his soon-to-be love interest, the prostitute-cum-madam Wendy, waxes lyrical about the joys of selling sex.</p>
<p>Needless to say, the path of true love does not run smooth. Factor in highly confused nuns, a coconut shy and gross misuse of an ironing board, and you have a riotous romp featuring some of the most absurdly funny one-liners ever attributed to Satan.</p>
<p>Sadly though, the sparkling script is not demonstrated to its full potential here. Poor sound renders some of the musical numbers almost inaudible, while the somewhat lacklustre dance numbers detract from the otherwise strong performances.</p>
<h3>British Theatre Guide</h3>
<p>The music is catchy, the cast's voices are captivating, and Samantha Armsby's ingenious choreography is spot-on, highlighting Director Heather Newton's witty and inventive lyrics. <i>Apocalypse: The Musical </i>is a delightful bit of late-night entertainment, drawing on all the comedic possibilities offered by whores, nuns, milkmen, God, Satan, and Holy Cows.</p>
<p>In sharp contrast to many Fringe performers, this cast has what it takes to pull an audience into a story that lasts nearly an hour and a half and is as improbable as it is hysterical.</p>
<p>Satirically speaking, <i>Apocalypse</i> owes much to shows like<i> Batboy</i>, but as Mark Stanford's wide-eyed and innocent Charlie the Milkman serenades Sarah Lambie's Wendy the Whore, audiences may find they're laughing too hard to concentrate on the show's probable musical ancestry.</p>
<p>The best thing about this play is how consummately professional and well-played are each of the actors' parts. From the uber-expressive Daisy the Cow (Christian Carter) to the biblical deity with the voice of a Baptist preacher (Dom Carter) and the wickedly delightful (and delighted!) Satan (Fongphu Tran), each performer hits their marks and endears themselves to the audience at the same time.</p>
<p>Finally, the technical side of this performance is flawless, with everything from Ernest Merry's score to Rosaleen Newton and Cora Bates' costumes contributing exactly what's required to bring out the best of what's in Newton's script.</p>
<p>To top it all off, <i>Apocalypse</i> isn't just fluff - there's a political message about apathy and understanding tucked carefully in at the end. But it's done so skilfully, and so well marked out in the script, that unlike other shows that try to urge audiences to care a bit more about the world they live in, <i>Apocalypse </i>doesn't bash anyone over the head with its agenda and audiences that really want to can enjoy it just for its story.</p>
<p><i>Apocalypse</i> will no doubt piss off the fundamentalists and conservatives who were insulted by the BBC's broadcasting of <i>Jerry Springer: The Musical</i>, but if you're even vaguely left of centre, it's probably the best musical laugh you'll get on the Fringe.</p>
<h3>The Herald</h3>
<p>The end of the world is nigh. God and Satan prepare for Armageddon. God enlists a milkman to lead his army, Satan chooses a madam and somehow steals a group of nuns from under God's nose, and thus begins a lark where the two generals fall in love and cows, angels, nuns and callgirls get caught up in all sorts of dottiness.</p>
<p>A couple of samples: the nuns, having captured the milkman, decide to tie him to an ironing board rather than a crucifix, although one opines that she's seen that sort of thing done before. Then a reformed callgirl expresses relief that, from now on, when someone says "heigh-ho", they won't be talking to her.</p>
<p>Strong performances from a likeable young cast help to make this an enjoyable late-night diversion. Oh, and the devil doesn't get all the best tunes.</p>
